### ISSUE TITLE
Problem with express checkout

### ISSUE THREAD

**Issue by HabedyOmid** [srmklive/laravel-paypal-demo#11]
an error "Method [getCheckoutData] does not exist." occurs while clicking on express checkout link and it triggers the getExpressCheckout() function. its happening in line:

        $cart = $this->getCheckoutData($recurring);

By the way i am using laravel 5.4 if it may change anything.

**Comment by srmklive** [comment]
Kindly use the 5.4 branch of this demo app. You shouldn't see this error anyway.
