### ISSUE TITLE
We’re sorry Things don’t appear to be working at the moment.

### ISSUE THREAD

**Issue by himalaya-ahuja** [srmklive/laravel-paypal-demo#12]
Hi i cloned your repository "laravel-paypal-demo" and configured the app exactly as you mentioned in installation steps , i replaced the Sandbox api credentials with mine , then when i run the app , and choose Express Checkout , it redirects me to paypal login and i enter my sandbox buyer account credentials , then after login i get redirected to  this paypal page displaying " We’re sorry Things don’t appear to be working at the moment.
<img width="955" alt="paypal_error" src="https://user-images.githubusercontent.com/31985973/30476959-497d2918-9a29-11e7-9e7d-a9d70350d4b1.PNG">
"

**Comment by srmklive** [comment]
This is an issue on paypal's end.

**Comment by himalaya-ahuja** [comment]
but i checked your online demo , (https://laravel-paypal-demo.srmk.info/) and i used my sandbox buyer account to buy , and it worked  ! It seems unlikely that the issue is at paypal's end.. i can give you more info if you need , please help me out here buddy.

**Comment by srmklive** [comment]
Could be an issue with paypal api credentials or the account which contains your sandbox accounts is suspended.

**Comment by himalaya-ahuja** [comment]
I copied and pasted the sandbox api credentials as it is as paypal showed in sandbox account's 'facilitator's api credentials' and the account seems active and email verified , anything else might be causing problem?

**Comment by himalaya-ahuja** [comment]
<img width="670" alt="paypal_my account" src="https://user-images.githubusercontent.com/31985973/30479471-096a9d74-9a33-11e7-97ca-3d6d89981837.PNG">

**Comment by himalaya-ahuja** [comment]
Solved the issue : The facilitator sandbox account's country had to be changed to US.
