### ISSUE TITLE
Checkout problem

### ISSUE THREAD

**Issue by FabiGjuzi** [srmklive/laravel-paypal-demo#13]
I am using laravel 5.5 and when I click express checkout link this error fires:

The Response content must be a string or object implementing __toString(), "object" given.

**Comment by srmklive** [comment]
I am running the demo app on Laravel 5.5, and the process is working correctly. You may need to run `composer update` to update your dependencies.

**Comment by FabiGjuzi** [comment]
I am trying and $response['paypal_link'] is empty at getExpressCheckout method.

**Comment by FabiGjuzi** [comment]
`public function getExpressCheckout(Request $request)
    {
        $recurring = ($request->get('mode') === 'recurring') ? true : false;
        $cart = $this->getCheckoutData($recurring);

        try {
            $response = $this->provider->setExpressCheckout($cart, $recurring);

            return redirect($response['paypal_link']);
        } catch (\Exception $e) {
            $invoice = $this->createInvoice($cart, 'Invalid');

            session()->put(['code' => 'danger', 'message' => "Error processing PayPal payment for Order $invoice->id!"]);
        }
    }`

**Comment by FabiGjuzi** [comment]
`public function getExpressCheckout(Request $request)
    {
        $recurring = ($request->get('mode') === 'recurring') ? true : false;
        $cart = $this->getCheckoutData($recurring);

        try {
            $response = $this->provider->setExpressCheckout($cart, $recurring);

            return redirect($response['paypal_link']);
        } catch (\Exception $e) {
            $invoice = $this->createInvoice($cart, 'Invalid');

            session()->put(['code' => 'danger', 'message' => "Error processing PayPal payment for Order $invoice->id!"]);
        }
    }`

**Comment by FabiGjuzi** [comment]
`public function getExpressCheckout(Request $request)
    {
        $recurring = ($request->get(\'mode\') === \'recurring\') ? true : false;
        $cart = $this->getCheckoutData($recurring);

        try {
            $response = $this->provider->setExpressCheckout($cart, $recurring);

            return redirect($response[\'paypal_link\']);
        } catch (\Exception $e) {
            $invoice = $this->createInvoice($cart, \'Invalid\');

            session()->put(['code' => 'danger', 'message' => "Error processing PayPal payment for Order $invoice->id!"]);
        }
    }`

**Comment by FabiGjuzi** [comment]
public function getExpressCheckout(Request $request)
    {
        $recurring = ($request->get('mode') === 'recurring') ? true : false;
        $cart = $this->getCheckoutData($recurring);

        try {
            $response = $this->provider->setExpressCheckout($cart, $recurring);

            return redirect($response['paypal_link']);
        } catch (\Exception $e) {
            $invoice = $this->createInvoice($cart, 'Invalid');

            session()->put(['code' => 'danger', 'message' => "Error processing PayPal payment for Order $invoice->id!"]);
        }
    }

**Comment by FabiGjuzi** [comment]
this is response json:

{"TIMESTAMP":"2017-10-05T13:01:48Z","CORRELATIONID":"877d9bc7d6440","ACK":"Failure","VERSION":"123","BUILD":"39665128","L_ERRORCODE0":"10412","L_SHORTMESSAGE0":"Duplicate invoice","L_LONGMESSAGE0":"Payment has already been made for this InvoiceID.","L_SEVERITYCODE0":"Error","paypal_link":null}

**Comment by srmklive** [comment]
You need to provide a unique invoice id preferably with a prefix to PayPal.

**Comment by FabiGjuzi** [comment]
Thank you very much.
I fixed my problem.

**Comment by LainC156** [comment]
> You need to provide a unique invoice id preferably with a prefix to PayPal.

Can you give me an example of how the invoice_id format can be? thank you
