### ISSUE TITLE
[Question] Checkout redirect paypal url is null

### ISSUE THREAD

**Issue by yuliantosb** [srmklive/laravel-paypal-demo#15]
Hello sir, I just copy this repository and I do the instruction but there's some error,
in line

```
$response = $this->provider->setExpressCheckout($cart, $recurring);
return redirect($response['paypal_link']);
// line 54
```

the response is error and paypal_link is null, is there something that I missing?
Please help me. Thanks :)

**Comment by srmklive** [comment]
You need to set a unique invoice id. Preferably add a prefix like `MYPAYPALAPP_1` etc.
