### ISSUE TITLE
Object of class Illuminate\Routing\Redirector could not be converted to string

### ISSUE THREAD

**Issue by enriqueplace** [srmklive/laravel-paypal-demo#16]
Hi, 

I installed demo and tried the following url http://localhost:8000/paypal/ec-checkout

(with last version of Laravel, 5.5)

ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Routing\Redirector could not be converted to string

**Comment by srmklive** [comment]
I have cloned the repo separately in a new directory & tested it. But still can't replicate what you have reported here.

**Comment by ladaposamuel** [comment]
Hello check out my solution here
#18

**Comment by m7mdphp** [comment]
I installed demo and tried the following url http://localhost:8000/paypal/ec-checkout

ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Routing\Redirector could not be converted to string

"Object of class Illuminate\Routing\Redirector could not be converted to string"

**Comment by it277** [comment]
![Desktop screenshot](https://user-images.githubusercontent.com/52188184/65575857-638c4d00-df8e-11e9-9900-69ff7f143bc3.png)
Hi
I installed demo and tried the following url http://localhost:8000/paypal/ec-checkout

I am also getting same error.
ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Routing\Redirector could not be converted to string

**Comment by phelicio** [comment]
same here.

**Comment by marc-lassiter** [comment]
How did you fix it?

**Comment by damienburdo** [comment]
I tryed with json_encode.
It's finally failed at "    $this->subtotal = isset($data['subtotal']) ? $data['subtotal'] : $data['total'];"
->Cannot use object of type stdClass as array
...

**Comment by mayankpal100** [comment]
I have the same issue, and is have resolved this issue,
guys Do verify your sandbox all details and retry again (it works for me 100%)
