### ISSUE TITLE
Store Name

### ISSUE THREAD

**Issue by ladaposamuel** [srmklive/laravel-paypal-demo#18]
I've installed this demo successfully and published the config file with my own API credentials,
When i attempt to pay i get the wrong store name ( not the one i used while setting up the sandbox account)
And the sandbox business account wont get credited even though the buyer's account was debited .

Thanks

**Comment by ladaposamuel** [comment]
![image](https://user-images.githubusercontent.com/9302799/36514210-b21c7ad8-1773-11e8-8e4c-a3b4907cb728.png)

**Comment by srmklive** [comment]
You need to provide the correct api credentials in `.env` file. It seems to me that you are using the sandbox credentials provided in the `.env.example` file.

**Comment by ladaposamuel** [comment]
Not at all I'm using my own env.

**Comment by ladaposamuel** [comment]
Thank you for your response.
I have re set up the again to be sure and changed all the settings now im getting this.
Duplicate of #16

**Comment by ladaposamuel** [comment]
Thank you once again.
You do not need to worry anymore as I've been able to resolve this issue myself.
The problem was with the API credentials i changed them and its fine now
