### ISSUE TITLE
Illuminate\Routing\Redirector

### ISSUE THREAD

**Issue by GBCC-WeDevGames** [srmklive/laravel-paypal-demo#19]
ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Routing\Redirector could not be converted to string

I got this error after following all the steps how to run the demo. After clicking the links this error appears.

**Comment by juan18a** [comment]
Friend the demo presents the following error:

ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Routing\Redirector could not be converted to string

I do not know if it has relation with the setExpressCheckout method, I need your help I am interested in creating a payment module.

**Comment by jieyu98** [comment]
Encountering this issue as well. Anyone has a solution?

**Comment by raihancse104** [comment]
Dear @srmklive,

This demo application show this error

**ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Routing\Redirector could not be converted to string**

i don't find a solution.  Just installing your demo application and doing as you processed. Please help me to solve this issue.

**Comment by srmklive** [comment]
Can't replicate this issue on my end.

**Comment by shamamit11** [comment]
@srmklive It does not mean you cannot replicate the issue then you just close it. All the people who tried your code are facing the same problem means there is a problem. Even I tried and used my own Paypal Credentials but it is not working and says - ****Object of class Illuminate\Routing\Redirector could not be converted to string****

**Comment by ruinobreferreira** [comment]
I have the same issue.

On development environment all went ok.
On production environment I get the same issue.

I'm using ExpressCheckout and tried to re-generate Paypal credentials and none of this worked.

@srmklive Can you check it and re-open this issue?

**Comment by ruinobreferreira** [comment]
@officialwedevgames @juan18a @jieyu98 @raihancse104 
Any clue on how to solve this?

**Comment by madhavinit** [comment]
i am also getting this error "Object of class Illuminate\Routing\Redirector could not be converted to string"

**Comment by RichieMcMullen** [comment]
Yea same here. Works in sandbox, fails in live mode. 

> Object of class Illuminate\Routing\Redirector could not be converted to string

**Comment by marc-lassiter** [comment]
Having the same problem.. anyone solve this yet?

**Comment by abhishekjain-itsme** [comment]
I am also getting same error "Object of class Illuminate\Routing\Redirector could not be converted to string"

Any solution???

**Comment by kamrankwl** [comment]
Kindly check and login your account (Developer) first . if there will be no issue then reload page again

**Comment by texiontech** [comment]
I'v this issue too. but i have resolve this problem by dd the $response on set setExpressCheckout

it's happen because your invoice is  Duplicate

array:10 [▼
  "TIMESTAMP" => "2020-03-19T04:12:56Z"
  "CORRELATIONID" => "e487813af28cf"
  "ACK" => "Failure"
  "VERSION" => "123"
  "BUILD" => "54296257"
  "L_ERRORCODE0" => "10412"
  "L_SHORTMESSAGE0" => "Duplicate invoice"
  "L_LONGMESSAGE0" => "Payment has already been made for this InvoiceID."
  "L_SEVERITYCODE0" => "Error"
  "paypal_link" => null
]

**Comment by marc-lassiter** [comment]
@yotewach It has to do with your keys being off. You might be using the wrong keys.

**Comment by c0de-intention** [comment]
For anyone who is wondering what those wrong details are, please use the API credentials with this _api1.business.example.com in it. also use the following from API credentials in the sandbox account details tab: username, password and signature as the 3 credentials in the .env Also don't forget to run php artisan config:cache after fixing them.

**Comment by ginoesaul** [comment]
Have the same problem and i dont know how to fix it
