### ISSUE TITLE
Demo setup

### ISSUE THREAD

**Issue by testsoftuvo** [srmklive/laravel-paypal-demo#21]
(1/1) ErrorExceptionUndefined index: billing_type
--
in PayPalRequest.php line 188
at HandleExceptions->handleError(8, 'Undefined index: billing_type', '/var/www/html/paypaldemo/vendor/srmklive/paypal/src/Traits/PayPalRequest.php', 188,array('credentials' => array('mode' => 'sandbox', 'sandbox' => array('username' => 'testmerchant_api1.srmk.info', 'password' => '4C4ADYAFC495VDP2', 'secret' => 'AFcWxV21C7fd0v3bYYYRCpSSRl31AALp5e0GQK12fLrxYB.TY6Er883L', 'certificate' => '', 'app_id' => 'APP-80W284485P519543T'), 'live' =>array('username' => '', 'password' => '', 'secret' => '', 'certificate' => '', 'app_id' => ''), 'payment_action' => 'Sale', 'currency' => 'USD', 'notify_url' => '', 'locale' => '', 'invoice_prefix' => 'PAYPALDEMOAPP')))

**Comment by srmklive** [comment]
You may need to change invoice prefix. The demo app is working
