### ISSUE TITLE
Why my logo is not working?

### ISSUE THREAD

**Issue by mangao05** [srmklive/laravel-paypal-demo#27]
i've used this logo https://upload.wikimedia.org/wikipedia/commons/c/c3/Eye.png

` $options = [
                'BRANDNAME' => 'Havendwell',
                'LOGOIMG' => 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Eye.png',
                'CHANNELTYPE' => 'Merchant'
            ];  
            $provider->addOptions($options); `

**Comment by srmklive** [comment]
Have a look at PayPal documentation link for this. Do note that the image provided should be accessible though
