### ISSUE TITLE
How to get txn_id in paypal in your package? 

### ISSUE THREAD

**Issue by kanu786** [srmklive/laravel-paypal-demo#30]
I am using your package. But after getting response i am getting txn_id from paypal. can you please   help us for this issue?
 
         $response = $this->provider->getExpressCheckoutDetails($token);
        //echo "<pre>"; print_r($response); die;
         if (in_array(strtoupper($response['ACK']), ['SUCCESS', 'SUCCESSWITHWARNING'])) {
         }

**Comment by srmklive** [comment]
You need to use doExpressCheckoutPayment  method to get tranaction id.
