### ISSUE TITLE
How to get Adaptive Payment details on Success and Cancel Page ?

### ISSUE THREAD

**Issue by aliasgarvanak** [srmklive/laravel-paypal-demo#34]
How to get the Payment details of Adaptive Payment on success and cancel page ?

**Comment by karan-bacancy** [comment]
Hello @aliasgarvanak  @srmklive 

Did you get the solution..? i have same problem.. Also i got error of **Undefined index: payKey** for adaptive payment integration. it's not create payKey from  **createPayRequest** function. This function works fine before but suddenly it's stop to working..

DO you have any solution or idea how can i resovled it..?
I have used laravel  framework  6.2  and PHP version 7.3.5 and lib version 1.7

Please give me appropriate solution..

Thanks.
