### ISSUE TITLE
Sorry, we weren’t able to complete your payment or set up preapproved payments at this time.

### ISSUE THREAD

**Issue by AbdoCode** [srmklive/laravel-paypal-demo#38]
Hi, i'm trying to make a recurring payment with these exact steps

- **setExpressCheckout**
- **getExpressCheckoutDetails**
- **createMonthlySubscription**

And i'm getting this message when redirecting me to paypal account

**Sorry, we weren’t able to complete your payment or set up preapproved payments at this time.**

Is this issue related to the mechant account settings or what? How can i solve it ???

![image](https://user-images.githubusercontent.com/13152717/83398072-f5423900-a3fe-11ea-8790-3ba3dd1ba014.png)

**Comment by nazarialireza** [comment]
Same issue here, and i just never use recurring payment, but I'm still looking to solve issue and use recurring payment in my application.

**Comment by omaralakel** [comment]
did you find a solution for that guys?
