### ISSUE TITLE
Set Paid column on invoice

### ISSUE THREAD

**Issue by bhaidar** [srmklive/laravel-paypal-demo#49]
Hello @srmklive,

Thank you for this nice package! 

I am looking at the demo code and noticed the following when creating a new invoice:

```
if (!strcasecmp($status, 'Completed') || !strcasecmp($status, 'Processed')) {
            $invoice->paid = 1;
        } else {
            $invoice->paid = 0;
        }
```

The code above marks an invoice as paid when it is not completed or processed. Is this the correct logic? Shouldn't be the other way around?

Thanks
Bilal

**Comment by srmklive** [comment]
https://www.php.net/manual/en/function.strcasecmp

Look at the documentation for the function, you will then understand.
